#!/usr/bin/env node
/**
 * Generate Quiz Index
 *
 * Scans the quizzes/ directory and generates src/data/quizIndex.ts
 * with metadata for all available quizzes.
 *
 * Run with: node scripts/generateQuizIndex.js
 * or: npm run generate-quiz-index
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '..');
const QUIZZES_DIR = path.join(PROJECT_ROOT, 'quizzes');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'src', 'data', 'quizIndex.ts');

const TOPICS = ['algebra', 'geometry', 'trigonometry', 'calculus', 'statistics', 'functions', 'measurement'];

/**
 * Recursively find all quiz.md files
 */
function findQuizFiles(dir) {
  const quizFiles = [];

  if (!fs.existsSync(dir)) {
    console.warn(`Warning: Directory ${dir} does not exist`);
    return quizFiles;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      quizFiles.push(...findQuizFiles(fullPath));
    } else if (entry.name === 'quiz.md') {
      quizFiles.push(fullPath);
    }
  }

  return quizFiles;
}

/**
 * Extract metadata from quiz markdown file
 */
function extractMetadata(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const { data } = matter(content);

    // Determine topic from file path
    const relativePath = path.relative(QUIZZES_DIR, filePath);
    const pathParts = relativePath.split(path.sep);
    const topic = pathParts[0];

    if (!TOPICS.includes(topic)) {
      console.warn(`Warning: Unknown topic "${topic}" for ${filePath}`);
    }

    // Convert absolute path to relative path for import
    const relativeFilePath = '/' + path.relative(PROJECT_ROOT, filePath).replace(/\\/g, '/');

    return {
      id: data.id || '',
      title: data.title || '',
      topic: data.topic || topic,
      difficulty: data.difficulty || 'medium',
      questionCount: data.questionCount || 0,
      createdFrom: data.createdFrom,
      dateGenerated: data.dateGenerated || new Date().toISOString().split('T')[0],
      estimatedTime: data.estimatedTime,
      tags: data.tags || [],
      description: data.description,
      filePath: relativeFilePath
    };
  } catch (error) {
    console.error(`Error processing ${filePath}:`, error.message);
    return null;
  }
}

/**
 * Generate TypeScript quiz index file
 */
function generateIndexFile(quizzes) {
  const template = `/**
 * Auto-generated quiz index
 * This file is generated by scripts/generateQuizIndex.js
 * Do not edit manually - run \`npm run generate-quiz-index\` to update
 */

export interface QuizMetadata {
  id: string;
  title: string;
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  questionCount: number;
  createdFrom?: string;
  dateGenerated: string;
  estimatedTime?: number;
  tags?: string[];
  description?: string;
  filePath: string;
}

export const quizzes: QuizMetadata[] = ${JSON.stringify(quizzes, null, 2)};

export function getQuizzesByTopic(topic: string): QuizMetadata[] {
  return quizzes.filter(quiz => quiz.topic === topic);
}

export function getQuizzesByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): QuizMetadata[] {
  return quizzes.filter(quiz => quiz.difficulty === difficulty);
}

export function getQuizById(id: string): QuizMetadata | undefined {
  return quizzes.find(quiz => quiz.id === id);
}

export function searchQuizzes(query: string): QuizMetadata[] {
  const lowerQuery = query.toLowerCase();
  return quizzes.filter(quiz =>
    quiz.title.toLowerCase().includes(lowerQuery) ||
    quiz.topic.toLowerCase().includes(lowerQuery) ||
    quiz.tags?.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    quiz.description?.toLowerCase().includes(lowerQuery)
  );
}

export const topics = ${JSON.stringify(TOPICS)} as const;
export type Topic = typeof topics[number];
`;

  return template;
}

/**
 * Main execution
 */
function main() {
  console.log('Generating quiz index...');

  // Find all quiz files
  const quizFiles = findQuizFiles(QUIZZES_DIR);
  console.log(`Found ${quizFiles.length} quiz file(s)`);

  // Extract metadata from each quiz
  const quizzes = quizFiles
    .map(extractMetadata)
    .filter(quiz => quiz !== null)
    .sort((a, b) => a.topic.localeCompare(b.topic) || a.title.localeCompare(b.title));

  console.log(`Processed ${quizzes.length} quiz(zes)`);

  // Generate index file
  const indexContent = generateIndexFile(quizzes);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write to file
  fs.writeFileSync(OUTPUT_FILE, indexContent, 'utf8');

  console.log(`Quiz index generated successfully at: ${OUTPUT_FILE}`);

  // Print summary by topic
  console.log('\nQuizzes by topic:');
  TOPICS.forEach(topic => {
    const count = quizzes.filter(q => q.topic === topic).length;
    if (count > 0) {
      console.log(`  ${topic}: ${count}`);
    }
  });
}

main();
