/**
 * Auto-generated quiz index
 * This file is generated by scripts/generateQuizIndex.js
 * Do not edit manually - run `npm run generate-quiz-index` to update
 */

export interface QuizMetadata {
  id: string;
  title: string;
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
  questionCount: number;
  createdFrom?: string;
  dateGenerated: string;
  estimatedTime?: number;
  tags?: string[];
  description?: string;
  filePath: string;
}

export const quizzes: QuizMetadata[] = [
  {
    "id": "algebra-chapter-1-001",
    "title": "Algebra Chapter 1: Foundations of Algebra",
    "topic": "algebra",
    "difficulty": "medium",
    "questionCount": 20,
    "createdFrom": "Algebra Chapter 1.pdf",
    "dateGenerated": "2026-03-23",
    "estimatedTime": 30,
    "tags": [
      "algebraic-expressions",
      "substitution",
      "like-terms",
      "expanding",
      "factorising",
      "algebraic-fractions",
      "binomials"
    ],
    "description": "Covers the full Year 9 Algebra Chapter 1: writing and simplifying expressions, substitution, algebraic fractions, expanding and factorising.",
    "filePath": "/quizzes/algebra/algebra-chapter-1/quiz.md"
  },
  {
    "id": "algebra-sample-linear-equations",
    "title": "Linear Equations Practice",
    "topic": "algebra",
    "difficulty": "medium",
    "questionCount": 3,
    "createdFrom": "sample-textbook.pdf",
    "dateGenerated": "2025-11-02",
    "estimatedTime": 5,
    "tags": [
      "linear-equations",
      "solving",
      "variables"
    ],
    "description": "Practice solving basic linear equations with one variable",
    "filePath": "/quizzes/algebra/sample-linear-equations/quiz.md"
  },
  {
    "id": "geometry-area-and-volume-measurement",
    "title": "Area and Volume: Measurement Practice",
    "topic": "geometry",
    "difficulty": "medium",
    "questionCount": 24,
    "createdFrom": "Math Chapter 5 Area and Volume.pdf",
    "dateGenerated": "2025-11-02",
    "estimatedTime": 30,
    "tags": [
      "area",
      "volume",
      "measurement",
      "circles",
      "prisms",
      "cylinders",
      "spheres",
      "composite-shapes",
      "perimeter",
      "circumference"
    ],
    "description": "Comprehensive practice on calculating areas and volumes of 2D and 3D shapes including circles, rectangular prisms, cylinders, spheres, and composite figures",
    "filePath": "/quizzes/geometry/area-and-volume-measurement/quiz.md"
  },
  {
    "id": "measurement-year-8-exam-001",
    "title": "Year 8 Measurement Exam - Area and Volume",
    "topic": "measurement",
    "difficulty": "hard",
    "questionCount": 24,
    "createdFrom": "Math Chapter 5 Area and Volume.pdf, Year 8 Task 4 past papers.pdf",
    "dateGenerated": "2025-11-02",
    "estimatedTime": 60,
    "tags": [
      "area",
      "volume",
      "perimeter",
      "conversions",
      "capacity",
      "measurement",
      "year-8"
    ],
    "description": "Comprehensive 1-hour measurement exam covering unit conversions, perimeter, area, volume, and capacity. Questions progress from easy to hard.",
    "filePath": "/quizzes/measurement/year-8-measurement-exam/quiz.md"
  },
  {
    "id": "statistics-data-analysis-chapter-9-001",
    "title": "Data Analysis Chapter 9: Analysing Data",
    "topic": "statistics",
    "difficulty": "medium",
    "questionCount": 20,
    "createdFrom": "Chapter 9 Data Analysis.pdf",
    "dateGenerated": "2026-03-23",
    "estimatedTime": 30,
    "tags": [
      "mean",
      "median",
      "mode",
      "range",
      "outlier",
      "histogram",
      "stem-and-leaf",
      "distribution",
      "skewness",
      "sampling",
      "categorical-data",
      "numerical-data"
    ],
    "description": "Covers Year 9 Statistics Chapter 9: measures of centre and spread, histograms, stem-and-leaf plots, distribution shape, comparing data sets, and types of data.",
    "filePath": "/quizzes/statistics/data-analysis-chapter-9/quiz.md"
  },
  {
    "id": "data-analysis-chapter-9-hard-001",
    "title": "Data Analysis Chapter 9: Hard Questions",
    "topic": "statistics",
    "difficulty": "hard",
    "questionCount": 20,
    "createdFrom": "Chapter 9 Data Analysis.pdf",
    "dateGenerated": "2026-03-23",
    "estimatedTime": 45,
    "tags": [
      "mean",
      "median",
      "mode",
      "range",
      "stem-and-leaf",
      "dot-plot",
      "histogram",
      "distribution",
      "skew",
      "outliers",
      "sampling",
      "stratified-sample",
      "comparing-data"
    ],
    "description": "Challenging Year 9 Data Analysis questions covering measures of centre and spread, distribution shapes, comparing data sets, and sampling methods.",
    "filePath": "/quizzes/statistics/data-analysis-chapter-9-hard/quiz.md"
  },
  {
    "id": "statistics-data-investigation",
    "title": "Data Investigation: Statistics Practice",
    "topic": "statistics",
    "difficulty": "medium",
    "questionCount": 30,
    "createdFrom": "Chapter 7 Data Investigation.pdf",
    "dateGenerated": "2025-11-02",
    "estimatedTime": 40,
    "tags": [
      "statistics",
      "data-analysis",
      "mean",
      "median",
      "mode",
      "graphs",
      "data-displays",
      "frequency-tables",
      "stem-and-leaf",
      "histograms",
      "sampling"
    ],
    "description": "Comprehensive practice on data investigation including statistical measures (mean, median, mode, range), data displays (graphs, charts, plots), and data analysis techniques",
    "filePath": "/quizzes/statistics/data-investigation/quiz.md"
  }
];

export function getQuizzesByTopic(topic: string): QuizMetadata[] {
  return quizzes.filter(quiz => quiz.topic === topic);
}

export function getQuizzesByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): QuizMetadata[] {
  return quizzes.filter(quiz => quiz.difficulty === difficulty);
}

export function getQuizById(id: string): QuizMetadata | undefined {
  return quizzes.find(quiz => quiz.id === id);
}

export function searchQuizzes(query: string): QuizMetadata[] {
  const lowerQuery = query.toLowerCase();
  return quizzes.filter(quiz =>
    quiz.title.toLowerCase().includes(lowerQuery) ||
    quiz.topic.toLowerCase().includes(lowerQuery) ||
    quiz.tags?.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    quiz.description?.toLowerCase().includes(lowerQuery)
  );
}

export const topics = ["algebra","geometry","trigonometry","calculus","statistics","functions","measurement"] as const;
export type Topic = typeof topics[number];
